parameters:
    app.name: yolo
    debug: false

services:
    front_controller:
        class: Yolo\FrontController
        arguments:
            - @http_kernel

    http_kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments:
            - @dispatcher
            - @controller_resolver

    dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver
        arguments:
            - @?logger

    route_builder:
        class: Yolo\RouteBuilder
        arguments:
            - @routes

    routes:
        class: Symfony\Component\Routing\RouteCollection

    url_matcher:
        class: Symfony\Component\Routing\Matcher\UrlMatcher
        arguments:
            - @routes
            - @request_context

    request_context:
        class: Symfony\Component\Routing\RequestContext

    exception_controller:
        class: Yolo\ExceptionController
        arguments:
            - @exception_handler

    exception_handler:
        class: Symfony\Component\HttpKernel\Debug\ExceptionHandler
        arguments:
            - %debug%

    listener.router:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
            - @url_matcher
            - @request_context
            - @?logger
        tags:
            - { name: kernel.event_subscriber }

    listener.response:
        class: Symfony\Component\HttpKernel\EventListener\ResponseListener
        arguments:
            - UTF-8
        tags:
            - { name: kernel.event_subscriber }

    listener.exception:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
            - [@exception_controller, 'handle']
            - @?logger
        tags:
            - { name: kernel.event_subscriber }

    listener.request_parameter:
        class: Yolo\EventListener\RequestParameterListener
        tags:
            - { name: kernel.event_subscriber }

    listener.string_response:
        class: Yolo\EventListener\StringResponseListener
        tags:
            - { name: kernel.event_subscriber }
